import Head from 'next/head'

// import ExcaliburGame from '@/games/ninjaRun/ExcaliburGame'
import MultipleChoice from '@/games/trivia/MultipleChoice'
export default function Home() {
  return (
    <>
      <Head>
        <title>React Games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1>Games Test</h1>
      <MultipleChoice/>

    </>
  )
}
