import Head from 'next/head'
import NavigationBar from '@/components/navigation/NavigationBar'
import PaymentForm from '@/components/payment/PaymentView'
import Footer from '@/components/sections/Footer'
import { Box } from '@mui/material'
export default function Home() {
  return (
    <>
      <Head>
        <title>React Pages</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <NavigationBar/>
      
      <Box
      sx={{
        height:1,
        minHeight:'calc(100vh - 200px)',
        marginBottom:10
      }}>
        <PaymentForm/>
      </Box>

      <Footer/>

    </>
  )
}
