import { useState } from 'react'
import Head from 'next/head';
import NavigationBar from '@/components/navigation/NavigationBar';
import { 
    Container, TextField
} from '@mui/material'

export default function Test() {

    const [cardNumber, setCardNumber] = useState('');

    const handleCardNumberChange = (event:any) => {
        let input = event.target.value.replace(/\D/g, '');

        // Insert dashes after every 4 digits
        let formattedInput = '';
        for (let i = 0; i < input.length; i += 4) {
            formattedInput += input.slice(i, i + 4) + '-';
        }

        // Remove the trailing dash if exists
        if (formattedInput.endsWith('-')) {
            formattedInput = formattedInput.slice(0, -1);
        }

        // Update the state with the formatted input
        setCardNumber(formattedInput);
    };

    return (
    <>
        <Head>
            <title>React Pages | Test</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <NavigationBar/>

        <Container>
            <div>
                <label>Card Number:</label>
                <TextField
                    type="text"
                    value={cardNumber}
                    onChange={handleCardNumberChange}
                    placeholder="Enter card number"
                />
            </div>
        </Container>
 
    </>
  )
}
