import { useRef, useState } from 'react'
import Head from 'next/head';
import NavigationBar from '@/components/navigation/NavigationBar';
import { Box, Stack, CardMedia } from '@mui/material'
import { PdfDownloadButton } from '@/components/buttons/ActionButtons';
import { blueGrey } from '@mui/material/colors';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export default function Test() {
    const [ imageData, setImageData] = useState<string>("")

    const printRef = useRef<HTMLDivElement|null>(null);

    const handleDownload = async () => {

        // Wait for the component to render and capture it as an image
        const canvas = await html2canvas(printRef.current!);

        // Calculate PDF dimensions based on the captured canvas
        const imgData = canvas.toDataURL('image/png');
        const imgProps = canvas;
        const pdfWidth = imgProps.width * 0.75; // You might need to adjust the scaling factor
        const pdfHeight = imgProps.height * 0.75; // You might need to adjust the scaling factor

        // Create PDF using jsPDF library
        const pdf = new jsPDF({
            orientation: 'p',
            unit: 'mm',
            format: [pdfWidth, pdfHeight],
        });

        // Add captured image to the PDF
        pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);

        // Save the PDF
        pdf.save('component.pdf');
    };

    return (
    <>
        <Head>
            <title>React Pages | Test</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavigationBar/>

        <Box
            sx={{
                width:1,
                display:'flex',
                flexDirection:'column',
                alignItems:'center',
            }}
        >
            
            <PdfDownloadButton
                onClickHandler={handleDownload}
            />

            <CardMedia
                component="img"
                height={50}
                image={imageData}
                alt="visa money logo"
                sx={{
                    objectFit:'contain',
                }}
            />
            
            <Box
                ref={printRef} 
                sx={{ 
                    width:1, 
                    maxWidth:700, 
                    borderRadius:2,
                }}
            >
                <Stack
                    rowGap={3}
                    alignItems={"center"}
                    justifyContent={"center"}
                    sx={{
                        width:1,
                        borderRadius:1,
                        border:`1px solid ${blueGrey[500]}`,
                        pr:2,
                        pl:2,
                        pt:1,
                        pb:1.5
                    }}
                >

                
                    <Box
                        sx={{
                            width:1,
                            height:500,
                            backgroundColor:'red'
                        }}
                    />
                    <Box
                        sx={{
                            width:1,
                            height:500,
                            backgroundColor:'pink'
                        }}
                    />
                    <Box
                        sx={{
                            width:1,
                            height:500,
                            backgroundColor:'purple'
                        }}
                    />
                </Stack>
            </Box>
            

        </Box>
   

    </>
  )
}
